# mkerrtab.awk - generate dce_error_table.h, the built-in texts of dce_error_inq_text(), from
# the texts in dce_error_texts.txt and the status codes in rpcsts.idl and ncastat.idl.
#
# Usage: awk -f mkerrtab.awk dce_error_texts.txt rpcsts.idl ncastat.idl > dce_error_table.h
#
# Every "const unsigned32|long <symbol> = 0x<code>;" gets the text from dce_error_texts.txt,
# else the comment on its line (ncastat.idl), else one derived from the symbol
# (rpc_s_invalid_endpoint_format -> "invalid endpoint format"); the symbol is appended.
# Fails on a text for an unknown symbol, a code defined twice or a text longer than 159
# characters (the buffer size of the original DCE, dce_c_error_string_len 160).

FNR == 1 { file++ }

file == 1 {
    if ($0 ~ /^#/ || $0 ~ /^[ \t]*$/)
        next
    i = index($0, "\t")
    if (i == 0) {
        print "mkerrtab: no tab in: " $0 > "/dev/stderr"
        err = 1
        next
    }
    over[substr($0, 1, i - 1)] = substr($0, i + 1)
    next
}

/const[ \t]+(unsigned32|long)[ \t]+[A-Za-z0-9_]+[ \t]*=[ \t]*0[xX][0-9A-Fa-f]+/ {
    line = $0
    sub(/^.*const[ \t]+(unsigned32|long)[ \t]+/, "", line)
    name = line
    sub(/[ \t]*=.*$/, "", name)
    code = line
    sub(/^[^=]*=[ \t]*/, "", code)
    sub(/[^0-9A-Fa-fxX].*$/, "", code)
    code = tolower(code)
    comment = ""
    if (line ~ /\/\*.*\*\//) {
        comment = line
        sub(/^.*\/\*[ \t]*/, "", comment)
        sub(/[ \t]*\*\/.*$/, "", comment)
    }
    if (code in seen) {
        print "mkerrtab: code " code " defined twice: " seen[code] ", " name > "/dev/stderr"
        err = 1
    }
    seen[code] = name
    if (name in over) {
        text = over[name]
        used[name] = 1
    } else if (comment != "") {
        text = comment
    } else {
        text = name
        sub(/^(rpc_s_|rpc_m_|rpc_svc_desc_|ept_s_|uuid_s_|twr_s_|nca_s_)/, "", text)
        gsub(/_/, " ", text)
    }
    text = text " (" name ")"
    if (length(text) > 159) {
        print "mkerrtab: text of " name " longer than 159 characters" > "/dev/stderr"
        err = 1
    }
    gsub(/\\/, "\\\\", text)
    gsub(/"/, "\\\"", text)
    n++
    codes[n] = code
    texts[n] = text
}

END {
    for (s in over)
        if (!(s in used)) {
            print "mkerrtab: text for an unknown symbol: " s > "/dev/stderr"
            err = 1
        }
    if (n == 0) {
        print "mkerrtab: no status codes found" > "/dev/stderr"
        err = 1
    }
    if (err)
        exit 1
    print "/* Generated by mkerrtab.awk from dce_error_texts.txt, rpcsts.idl and ncastat.idl."
    print "   Do not edit. */"
    print ""
    print "static const struct"
    print "{"
    print "    unsigned int    code;"
    print "    const char      *text;"
    print "} dce_error_builtin_texts[] ="
    print "{"
    for (i = 1; i <= n; i++)
        printf "    { %su, \"%s\" },\n", codes[i], texts[i]
    print "};"
}
