#line 2 "nidl_l.c"

#line 4 "nidl_l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer nidl_yy_create_buffer
#define yy_delete_buffer nidl_yy_delete_buffer
#define yy_flex_debug nidl_yy_flex_debug
#define yy_init_buffer nidl_yy_init_buffer
#define yy_flush_buffer nidl_yy_flush_buffer
#define yy_load_buffer_state nidl_yy_load_buffer_state
#define yy_switch_to_buffer nidl_yy_switch_to_buffer
#define yyin nidl_yyin
#define yyleng nidl_yyleng
#define yylex nidl_yylex
#define yylineno nidl_yylineno
#define yyout nidl_yyout
#define yyrestart nidl_yyrestart
#define yytext nidl_yytext
#define yywrap nidl_yywrap
#define yyalloc nidl_yyalloc
#define yyrealloc nidl_yyrealloc
#define yyfree nidl_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE nidl_yyrestart(nidl_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int nidl_yyleng;

extern FILE *nidl_yyin, *nidl_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE nidl_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-nidl_yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < nidl_yyleng; ++yyl )\
                    if ( nidl_yytext[yyl] == '\n' )\
                        --nidl_yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nidl_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up nidl_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via nidl_yyrestart()), so that the user can continue scanning by
	 * just pointing nidl_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when nidl_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int nidl_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow nidl_yywrap()'s to do buffer switches
 * instead of setting up a fresh nidl_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void nidl_yyrestart (FILE *input_file  );
void nidl_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE nidl_yy_create_buffer (FILE *file,int size  );
void nidl_yy_delete_buffer (YY_BUFFER_STATE b  );
void nidl_yy_flush_buffer (YY_BUFFER_STATE b  );
void nidl_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void nidl_yypop_buffer_state (void );

static void nidl_yyensure_buffer_stack (void );
static void nidl_yy_load_buffer_state (void );
static void nidl_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER nidl_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE nidl_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE nidl_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE nidl_yy_scan_bytes (yyconst char *bytes,int len  );

void *nidl_yyalloc (yy_size_t  );
void *nidl_yyrealloc (void *,yy_size_t  );
void nidl_yyfree (void *  );

#define yy_new_buffer nidl_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        nidl_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nidl_yy_create_buffer(nidl_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        nidl_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nidl_yy_create_buffer(nidl_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *nidl_yyin = (FILE *) 0, *nidl_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int nidl_yylineno;

int nidl_yylineno = 1;

extern char *nidl_yytext;
#define yytext_ptr nidl_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up nidl_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	nidl_yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[172] =
    {   0,
        0,    0,   55,   53,    1,    1,   32,   44,   47,   35,
       24,   53,    8,   10,   12,   30,    4,   31,   53,   34,
       48,   48,    3,   11,   20,    6,   22,   17,    7,    9,
       29,   13,   18,   15,   36,   53,   35,   33,   44,   47,
       25,    0,    0,    0,    0,    0,   48,    5,   45,    0,
        0,   48,   48,   48,   49,   21,   26,   28,   27,   23,
        0,   19,    0,   37,    0,    0,    0,   42,    2,    0,
       43,    0,    0,   46,   50,   48,   48,   49,   49,   49,
       14,   16,    0,    0,    0,   43,   41,    0,   50,   50,
       49,   49,   38,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   40,   39,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   51,    0,   52,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   28,   28,   28,
        7,    7,    7,    7,    7,   30,    7,    7,    7,   31,
        7,    7,   32,    7,   33,    7,    7,   34,    7,    7,
       35,   36,   37,   38,    7,    1,   39,   28,   40,   28,

       28,   28,    7,    7,    7,    7,    7,   41,    7,    7,
        7,   42,    7,    7,   43,    7,   44,    7,    7,   45,
        7,    7,   46,   47,   48,   49,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[50] =
    {   0,
        1,    2,    3,    1,    4,    1,    5,    1,    1,    6,
        1,    1,    1,    1,    1,    7,    1,    1,    8,    8,
        1,    1,    1,    1,    1,    1,    8,    8,    8,    9,
        5,    5,    9,    5,    1,    1,    1,    1,    8,    8,
        9,    5,    5,    9,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[181] =
    {   0,
        0,   44,  286,  677,  677,  677,  259,    0,    0,  677,
      273,   48,   51,  677,  677,  677,  677,   36,  264,   44,
       68,   48,  677,  677,   35,  245,   36,  240,  677,  677,
      677,  677,  214,  677,  677,  255,   35,  677,    0,    0,
      677,  245,  244,  243,   67,   76,   53,  677,  677,  238,
       60,   91,   30,   41,   84,  677,  677,  677,  677,  677,
       68,  677,  235,  677,   97,  206,  191,  677,  677,  217,
      216,  110,  222,  677,  103,  677,  677,  101,   74,  110,
      677,  677,  210,  178,  162,  677,  677,  133,  677,  677,
      677,  677,  677,  173,  159,  136,  171,  158,  139,  155,

      141,  161,  117,  124,  164,  174,  171,  155,  677,  677,
      167,  189,  192,  195,  217,  220,  223,  153,  153,  245,
      248,  251,  273,  140,  276,  279,  301,  304,  138,  131,
      307,  329,  332,  335,  357,  129,  360,  363,  127,  385,
      388,  124,  391,  413,  416,  419,  441,   89,  444,  447,
      469,  472,  475,   73,  497,  500,  503,  525,  528,   59,
      531,  553,  556,  559,  588,  599,  601,  677,  603,  677,
      677,  615,  620,  629,  637,  645,  654,  663,  665,  668
    } ;

static yyconst flex_int16_t yy_def[181] =
    {   0,
      171,    1,  171,  171,  171,  171,  171,  172,  173,  171,
      171,  174,  175,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  176,  171,  171,  172,  173,
      171,  171,  171,  177,  175,  171,  171,  171,  171,  178,
      171,  171,  171,  171,  179,  171,  171,  171,  171,  171,
      171,  171,  176,  171,  171,  171,  171,  171,  171,  177,
      171,  171,  178,  171,  171,  171,  171,  179,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,

      171,  171,  171,  171,  171,  171,  171,  180,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
        0,  171,  171,  171,  171,  171,  171,  171,  171,  171
    } ;

static yyconst flex_int16_t yy_nxt[727] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,    9,    9,    9,    9,
        9,    9,    9,    9,   29,    4,   30,   31,    9,    9,
        9,    9,    9,    9,    9,   32,   33,   34,   35,   36,
       43,   37,   45,   45,   47,   47,   49,   56,   57,   59,
       60,   50,   76,   65,   51,   66,   52,   52,   45,   45,
       77,   47,   47,   76,   65,  162,   67,   53,   75,   75,
       54,   77,   53,   44,   51,   54,   52,   52,   53,  156,
       81,   54,   82,   53,   72,   72,   54,   53,   83,   83,

       54,   55,   72,   72,   72,  150,   91,   51,   53,   52,
       52,   54,   55,   79,   72,   72,   80,   91,  106,  106,
       53,   75,   75,   54,   79,  107,  107,   80,   88,   88,
       79,   53,   89,   80,   54,   90,   88,   88,   88,   92,
      144,   79,  141,   89,   80,  138,   90,  132,   88,   88,
       92,   96,   96,  131,   99,   99,  126,  102,  102,   96,
       96,   96,   99,   99,   99,  102,  102,  102,  121,  120,
      111,   96,   96,  110,   99,   99,  109,  102,  102,  105,
      105,  104,  108,  108,  103,  113,  113,  105,  105,  105,
      108,  108,  108,  113,  113,  113,  101,  100,   98,  105,

      105,   97,  108,  108,   95,  113,  113,  114,  114,   94,
      115,  115,   93,  116,  116,  114,  114,  114,  115,  115,
      115,  116,  116,  116,   74,   87,   86,  114,  114,   85,
      115,  115,   84,  116,  116,  117,  117,   64,  118,  118,
       74,  119,  119,  117,  117,  117,  118,  118,  118,  119,
      119,  119,   71,   69,   68,  117,  117,   64,  118,  118,
       62,  119,  119,  122,  122,   61,  123,  123,   58,  124,
      124,  122,  122,  122,  123,  123,  123,  124,  124,  124,
       48,   41,   38,  122,  122,  171,  123,  123,  171,  124,
      124,  125,  125,  171,  127,  127,  171,  128,  128,  125,

      125,  125,  127,  127,  127,  128,  128,  128,  171,  171,
      171,  125,  125,  171,  127,  127,  171,  128,  128,  129,
      129,  171,  130,  130,  171,  133,  133,  129,  129,  129,
      130,  130,  130,  133,  133,  133,  171,  171,  171,  129,
      129,  171,  130,  130,  171,  133,  133,  134,  134,  171,
      135,  135,  171,  136,  136,  134,  134,  134,  135,  135,
      135,  136,  136,  136,  171,  171,  171,  134,  134,  171,
      135,  135,  171,  136,  136,  137,  137,  171,  139,  139,
      171,  140,  140,  137,  137,  137,  139,  139,  139,  140,
      140,  140,  171,  171,  171,  137,  137,  171,  139,  139,

      171,  140,  140,  142,  142,  171,  143,  143,  171,  145,
      145,  142,  142,  142,  143,  143,  143,  145,  145,  145,
      171,  171,  171,  142,  142,  171,  143,  143,  171,  145,
      145,  146,  146,  171,  147,  147,  171,  148,  148,  146,
      146,  146,  147,  147,  147,  148,  148,  148,  171,  171,
      171,  146,  146,  171,  147,  147,  171,  148,  148,  149,
      149,  171,  151,  151,  171,  152,  152,  149,  149,  149,
      151,  151,  151,  152,  152,  152,  171,  171,  171,  149,
      149,  171,  151,  151,  171,  152,  152,  153,  153,  171,
      154,  154,  171,  155,  155,  153,  153,  153,  154,  154,

      154,  155,  155,  155,  171,  171,  171,  153,  153,  171,
      154,  154,  171,  155,  155,  157,  157,  171,  158,  158,
      171,  159,  159,  157,  157,  157,  158,  158,  158,  159,
      159,  159,  171,  171,  171,  157,  157,  171,  158,  158,
      171,  159,  159,  160,  160,  171,  161,  161,  171,  163,
      163,  160,  160,  160,  161,  161,  161,  163,  163,  163,
      171,  171,  171,  160,  160,  171,  161,  161,  171,  163,
      163,  164,  164,  171,  165,  165,  171,  166,  166,  164,
      164,  164,  165,  165,  165,  166,  166,  166,  171,  167,
      167,  164,  164,  171,  165,  165,  171,  166,  166,  168,

      169,  169,  167,  167,  169,  169,  171,  171,  171,  171,
      170,  171,  168,  171,  170,   39,   39,  171,  171,   39,
       39,   39,   39,   39,   40,  171,  171,   40,   40,   42,
       42,   42,   42,   42,  171,   42,   42,   42,   46,   46,
      171,  171,  171,  171,   46,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   70,   70,  171,   70,   70,   70,
       70,   70,   70,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   78,   78,  112,  112,    3,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,

      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171
    } ;

static yyconst flex_int16_t yy_chk[727] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
       12,    2,   13,   13,   18,   18,   20,   25,   25,   27,
       27,   20,   53,   37,   22,   37,   22,   22,   45,   45,
       54,   47,   47,   53,   37,  160,   37,   22,   51,   51,
       22,   54,   47,   12,   21,   47,   21,   21,   22,  154,
       61,   22,   61,   47,   46,   46,   47,   21,   65,   65,

       21,   21,   46,   46,   46,  148,   79,   52,   21,   52,
       52,   21,   21,   55,   46,   46,   55,   79,  103,  103,
       52,   75,   75,   52,   55,  104,  104,   55,   72,   72,
       78,   52,   75,   78,   52,   75,   72,   72,   72,   80,
      142,   78,  139,   75,   78,  136,   75,  130,   72,   72,
       80,   88,   88,  129,   96,   96,  124,   99,   99,   88,
       88,   88,   96,   96,   96,   99,   99,   99,  119,  118,
      108,   88,   88,  107,   96,   96,  106,   99,   99,  102,
      102,  101,  105,  105,  100,  111,  111,  102,  102,  102,
      105,  105,  105,  111,  111,  111,   98,   97,   95,  102,

      102,   94,  105,  105,   85,  111,  111,  112,  112,   84,
      113,  113,   83,  114,  114,  112,  112,  112,  113,  113,
      113,  114,  114,  114,   73,   71,   70,  112,  112,   67,
      113,  113,   66,  114,  114,  115,  115,   63,  116,  116,
       50,  117,  117,  115,  115,  115,  116,  116,  116,  117,
      117,  117,   44,   43,   42,  115,  115,   36,  116,  116,
       33,  117,  117,  120,  120,   28,  121,  121,   26,  122,
      122,  120,  120,  120,  121,  121,  121,  122,  122,  122,
       19,   11,    7,  120,  120,    3,  121,  121,    0,  122,
      122,  123,  123,    0,  125,  125,    0,  126,  126,  123,

      123,  123,  125,  125,  125,  126,  126,  126,    0,    0,
        0,  123,  123,    0,  125,  125,    0,  126,  126,  127,
      127,    0,  128,  128,    0,  131,  131,  127,  127,  127,
      128,  128,  128,  131,  131,  131,    0,    0,    0,  127,
      127,    0,  128,  128,    0,  131,  131,  132,  132,    0,
      133,  133,    0,  134,  134,  132,  132,  132,  133,  133,
      133,  134,  134,  134,    0,    0,    0,  132,  132,    0,
      133,  133,    0,  134,  134,  135,  135,    0,  137,  137,
        0,  138,  138,  135,  135,  135,  137,  137,  137,  138,
      138,  138,    0,    0,    0,  135,  135,    0,  137,  137,

        0,  138,  138,  140,  140,    0,  141,  141,    0,  143,
      143,  140,  140,  140,  141,  141,  141,  143,  143,  143,
        0,    0,    0,  140,  140,    0,  141,  141,    0,  143,
      143,  144,  144,    0,  145,  145,    0,  146,  146,  144,
      144,  144,  145,  145,  145,  146,  146,  146,    0,    0,
        0,  144,  144,    0,  145,  145,    0,  146,  146,  147,
      147,    0,  149,  149,    0,  150,  150,  147,  147,  147,
      149,  149,  149,  150,  150,  150,    0,    0,    0,  147,
      147,    0,  149,  149,    0,  150,  150,  151,  151,    0,
      152,  152,    0,  153,  153,  151,  151,  151,  152,  152,

      152,  153,  153,  153,    0,    0,    0,  151,  151,    0,
      152,  152,    0,  153,  153,  155,  155,    0,  156,  156,
        0,  157,  157,  155,  155,  155,  156,  156,  156,  157,
      157,  157,    0,    0,    0,  155,  155,    0,  156,  156,
        0,  157,  157,  158,  158,    0,  159,  159,    0,  161,
      161,  158,  158,  158,  159,  159,  159,  161,  161,  161,
        0,    0,    0,  158,  158,    0,  159,  159,    0,  161,
      161,  162,  162,    0,  163,  163,    0,  164,  164,  162,
      162,  162,  163,  163,  163,  164,  164,  164,    0,  165,
      165,  162,  162,    0,  163,  163,    0,  164,  164,  165,

      166,  166,  167,  167,  169,  169,    0,    0,    0,    0,
      166,    0,  167,    0,  169,  172,  172,    0,    0,  172,
      172,  172,  172,  172,  173,    0,    0,  173,  173,  174,
      174,  174,  174,  174,    0,  174,  174,  174,  175,  175,
        0,    0,    0,    0,  175,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  177,  177,    0,  177,  177,  177,
      177,  177,  177,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  179,  179,  180,  180,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,

      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[55] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 
    1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int nidl_yy_flex_debug;
int nidl_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *nidl_yytext;
#line 1 "nidl_l.l"
#line 2 "nidl_l.l"
 /*
 * 
 * (c) Copyright 1989 OPEN SOFTWARE FOUNDATION, INC.
 * (c) Copyright 1989 HEWLETT-PACKARD COMPANY
 * (c) Copyright 1989 DIGITAL EQUIPMENT CORPORATION
 * To anyone who acknowledges that this file is provided "AS IS"
 * without any express or implied warranty:
 *                 permission to use, copy, modify, and distribute this
 * file for any purpose is hereby granted without fee, provided that
 * the above copyright notices and this notice appears in all source
 * code copies, and that none of the names of Open Software
 * Foundation, Inc., Hewlett-Packard Company, or Digital Equipment
 * Corporation be used in advertising or publicity pertaining to
 * distribution of the software without specific, written prior
 * permission.  Neither Open Software Foundation, Inc., Hewlett-
 * Packard Company, nor Digital Equipment Corporation makes any
 * representations about the suitability of this software for any
 * purpose.
 * 
 */

/*
**  NAME:
**
**      IDL.L
**
**  FACILITY:
**
**      Interface Definition Language (IDL) Compiler
**
**  ABSTRACT:
**
**      This file defines the tokenizing rules for lexical analysis.
**
**  VERSION: DCE 1.0
**
*/



/*  Get definitions for token values    */
#define PROCESSING_LEX          /* Define before including nidl.h */
#define PROCESSING_NIDL_LEX     /* Define before including nidl.h */
#include <nidl.h>
#include <ctype.h>
#include <errors.h>
#include <nametbl.h>
#include <ast.h>
#include <astp.h>
#include <nidl_y.h>
#include <driver.h>
#include <command.h>
#include <flex_bison_support.h>

/* Tank Trap to stop non-flex lexxers */
/* The macro FLEX_SCANNER is defined and generated by FLEX */

#ifndef FLEX_SCANNER
This grammar file needs to be built with GNU Flex V2.4.6 or later.
  GNU Flex can be be obtained from ftp://prep.ai.mit.edu:/pub/gnu
#endif

extern YYSTYPE nidl_yylval;
extern int nidl_yylineno;

boolean search_attributes_table = false ;


static int nidl_yywrap(void)
{
   /* Free the Flex buffer, yy_curent_buffer and nidl_yy_delete_buffer() 
    * are FLEX interfaces to the internal buffering system.
    */

#if (YY_FLEX_MAJOR_VERSION == 2) && (YY_FLEX_MINOR_VERSION == 5)
   nidl_yy_delete_buffer(YY_CURRENT_BUFFER);
#else
   nidl_yy_delete_buffer(YY_CURRENT_BUFFER_LVALUE);
#endif
   nidl_yylineno = 1;
   return 1;
}

void commenteof (
#ifdef PROTO
    void
#endif
);

int nidl_yylex (
#ifdef PROTO
    void
#endif
);

int yylook (
#ifdef PROTO
    void
#endif
);

static void read_c_comment (
#ifdef PROTO
    void
#endif
);

static void yymark (
#ifdef PROTO
    void
#endif
);

static int yyuuid (
#ifdef PROTO
    char *s,
    nidl_uuid_t *uuid
#endif
);

static int yyolduuid (
#ifdef PROTO
    char *s,
    nidl_uuid_t *uuid
#endif
);



int KEYWORDS_screen (
#ifdef PROTO
    char *token,
    NAMETABLE_id_t *id
#endif
);

char *KEYWORDS_lookup_text (
#ifdef PROTO
    long token
#endif
);

int yyinput (
#ifdef PROTO
    void
#endif
);

int yyback (
#ifdef PROTO
    int *p,

    int m
#endif
);


/* regular definitions  */
#line 867 "nidl_l.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int nidl_yylex_destroy (void );

int nidl_yyget_debug (void );

void nidl_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE nidl_yyget_extra (void );

void nidl_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *nidl_yyget_in (void );

void nidl_yyset_in  (FILE * in_str  );

FILE *nidl_yyget_out (void );

void nidl_yyset_out  (FILE * out_str  );

int nidl_yyget_leng (void );

char *nidl_yyget_text (void );

int nidl_yyget_lineno (void );

void nidl_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int nidl_yywrap (void );
#else
extern int nidl_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( nidl_yytext, nidl_yyleng, 1, nidl_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( nidl_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( nidl_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, nidl_yyin))==0 && ferror(nidl_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(nidl_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int nidl_yylex (void);

#define YY_DECL int nidl_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after nidl_yytext and nidl_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( nidl_yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(nidl_yytext[nidl_yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 187 "nidl_l.l"

#line 1054 "nidl_l.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! nidl_yyin )
			nidl_yyin = stdin;

		if ( ! nidl_yyout )
			nidl_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			nidl_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				nidl_yy_create_buffer(nidl_yyin,YY_BUF_SIZE );
		}

		nidl_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of nidl_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 172 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 677 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < nidl_yyleng; ++yyl )
				if ( nidl_yytext[yyl] == '\n' )
					   
    nidl_yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 188 "nidl_l.l"
{ /* No action, and no return */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 189 "nidl_l.l"
{ /* GNU FLEX doesnt automatically track line #'s */
                  nidl_yylineno++; 
                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 192 "nidl_l.l"
{return(COLON);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 193 "nidl_l.l"
{return(COMMA);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 194 "nidl_l.l"
{return(DOTDOT);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 195 "nidl_l.l"
{return(EQUAL);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 196 "nidl_l.l"
{return(LBRACKET);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 197 "nidl_l.l"
{return(LPAREN);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 198 "nidl_l.l"
{return(RBRACKET);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 199 "nidl_l.l"
{return(RPAREN);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 200 "nidl_l.l"
{return(SEMI);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 201 "nidl_l.l"
{return(STAR);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 202 "nidl_l.l"
{return(LBRACE);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 203 "nidl_l.l"
{return(LBRACE);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 204 "nidl_l.l"
{return(RBRACE);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 205 "nidl_l.l"
{return(RBRACE);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 206 "nidl_l.l"
{return(QUESTION);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 207 "nidl_l.l"
{return(BAR);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 208 "nidl_l.l"
{return(BARBAR);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 209 "nidl_l.l"
{return(LANGLE);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 210 "nidl_l.l"
{return(LANGLEANGLE);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 211 "nidl_l.l"
{return(RANGLE);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 212 "nidl_l.l"
{return(RANGLEANGLE);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 213 "nidl_l.l"
{return(AMP);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 214 "nidl_l.l"
{return(AMPAMP);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 215 "nidl_l.l"
{return(LESSEQUAL);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 216 "nidl_l.l"
{return(GREATEREQUAL);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 217 "nidl_l.l"
{return(EQUALEQUAL);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 218 "nidl_l.l"
{return(CARET);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 219 "nidl_l.l"
{return(PLUS);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 220 "nidl_l.l"
{return(MINUS);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 221 "nidl_l.l"
{return(NOT);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 222 "nidl_l.l"
{return(NOTEQUAL);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 223 "nidl_l.l"
{return(SLASH);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 224 "nidl_l.l"
{return(PERCENT);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 225 "nidl_l.l"
{return(TILDE);}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 227 "nidl_l.l"
{ yymark() ;}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 228 "nidl_l.l"
{ acf_error(nidl_yylineno-1, NIDL_USETRANS, NULL); }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 229 "nidl_l.l"
{ acf_error(nidl_yylineno-1, NIDL_USETRANS, NULL); }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 230 "nidl_l.l"
{ acf_error(nidl_yylineno-1, NIDL_USETRANS, NULL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 232 "nidl_l.l"
{
    /* Simple escaped single quote character literal */
    nidl_yylval.y_char = '\'';
    return(CHAR);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 238 "nidl_l.l"
{
    /* Simple character constants */
    nidl_yylval.y_char = nidl_yytext [1];
    return(CHAR);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 244 "nidl_l.l"
{
    /* Character constants with an escape */
    if ((nidl_yyleng > 6) || (nidl_yyleng < 4)) {
          acf_error(nidl_yylineno, NIDL_INVCHARLIT, NULL);
          return(UNKNOWN);
    }
    switch (nidl_yytext[2]) {
        case 'n':   nidl_yylval.y_char = '\n'; break;
        case 't':   nidl_yylval.y_char = '\t'; break;
        case 'v':   nidl_yylval.y_char = '\v'; break;
        case 'b':   nidl_yylval.y_char = '\b'; break;
        case 'r':   nidl_yylval.y_char = '\r'; break;
        case 'f':   nidl_yylval.y_char = '\f'; break;
        case 'a':   nidl_yylval.y_char = AUDIBLE_BELL; break;
        case '\\':  nidl_yylval.y_char = '\\'; break;
        case '?':   nidl_yylval.y_char = '\?'; break;
        case '\'':  nidl_yylval.y_char = '\''; break;
        case '\"':  nidl_yylval.y_char = '\"'; break;
        case 'x' :  {
            /* Hex literal value */
            int char_value;
            if (sscanf((char *)&nidl_yytext[3],"%x",&char_value) != 1)
                acf_error(nidl_yylineno, NIDL_INVCHARLIT, NULL);
            else
            {
                nidl_yylval.y_char = (char )char_value;
                acf_warning(nidl_yylineno, NIDL_NONPORTCHAR, NULL);
            }
            break;
        }
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '7':   {
            /* Octal literal value */
            int char_value;
            if (sscanf((char *)&nidl_yytext[2],"%o",&char_value) != 1)
                acf_error(nidl_yylineno, NIDL_INVCHARLIT, NULL);
            else
            {
                nidl_yylval.y_char = (char )char_value;
                acf_warning(nidl_yylineno, NIDL_NONPORTCHAR, NULL);
            }
            break;
        }
        default:
            /* all others are illegal */
            acf_error(nidl_yylineno, NIDL_INVCHARLIT, NULL);
            return(UNKNOWN);
    }

    return (CHAR);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 301 "nidl_l.l"
{
    char stripped_string[max_string_len] __attribute__((__unused__));
    if (nidl_yytext[nidl_yyleng-1] == '\\')
        yymore(); /* Allow backslashed " within strings, look for next " */
    else {
    nidl_yylval.y_string = STRTAB_add_string((char *)&nidl_yytext[1]);
        if (input() == '\n')
            acf_error(nidl_yylineno, NIDL_STRUNTERM, NULL);
        return(STRING);
    }
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 313 "nidl_l.l"
{ read_c_comment(); }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 314 "nidl_l.l"
{ /* read_cpp_comment */ }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 316 "nidl_l.l"
{
    int token;
    NAMETABLE_id_t id;
    /* If id is too long, truncate it and issue a warning */
    if (nidl_yyleng > MAX_ID) {
        NAMETABLE_id_t id;
        char const *identifier;
        id = NAMETABLE_add_id((char *)nidl_yytext);
        NAMETABLE_id_to_string(id, &identifier);
        acf_warning(nidl_yylineno, NIDL_IDTOOLONG, identifier, MAX_ID, NULL);
        /* Truncate the string */
        nidl_yytext[MAX_ID] = '\0';
        id = NAMETABLE_add_id((char *)nidl_yytext);
    }
    if ((token = KEYWORDS_screen((char *)nidl_yytext, &id))==IDENTIFIER) {
        nidl_yylval.y_id = id;
    }
    else {
        nidl_yylval.y_id = NAMETABLE_NIL_ID;
    }
    return token;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 340 "nidl_l.l"
{
    int unsigned_int = false;
#if defined(vax) && defined(ultrix)
    float fval;
    char *fval_fmt = "%f";
#define FLOAT float
#else
    double fval;
    char *fval_fmt = "%lf";
#define FLOAT double
#endif

    /*
    ** Remove suffix for long and/or unsigned, if present
    */
    if ((nidl_yytext[nidl_yyleng-1] == 'L') ||
        (nidl_yytext[nidl_yyleng-1] == 'l') ||
        (nidl_yytext[nidl_yyleng-1] == 'U') ||
        (nidl_yytext[nidl_yyleng-1] == 'u'))
    {
        if ((nidl_yytext[nidl_yyleng-1] == 'U') ||
            (nidl_yytext[nidl_yyleng-1] == 'u'))
                unsigned_int = true;
        nidl_yytext[nidl_yyleng-1] = '\0';
        if ((nidl_yytext[nidl_yyleng-2] == 'L') ||
            (nidl_yytext[nidl_yyleng-2] == 'l') ||
            (nidl_yytext[nidl_yyleng-2] == 'U') ||
            (nidl_yytext[nidl_yyleng-2] == 'u'))
        {
            if ((nidl_yytext[nidl_yyleng-2] == 'U') ||
                (nidl_yytext[nidl_yyleng-2] == 'u'))
                    unsigned_int = true;
            nidl_yytext[nidl_yyleng-2] = '\0';
        }
    }

    /*
    ** Convert to a float to get overflow detection.
    */
    sscanf((char *)nidl_yytext, fval_fmt, &fval);
    nidl_yylval.y_int_info.int_val = 0;

    /*
    ** Throw out integers that are out of range.
    */
    if (unsigned_int &&
        ((strlen((char *)nidl_yytext) > 10)
        || (fval > (FLOAT)ASTP_C_ULONG_MAX)
        || (fval < (FLOAT)ASTP_C_ULONG_MIN)
        ))
        acf_error(nidl_yylineno, NIDL_INTOVERFLOW,
		  KEYWORDS_lookup_text(LONG_KW), NULL);
    else if ((strlen((char *)nidl_yytext) > 11) ||
        (fval > (FLOAT)ASTP_C_LONG_MAX) ||
        (fval < (FLOAT)ASTP_C_LONG_MIN)
        )
        acf_error(nidl_yylineno, NIDL_INTOVERFLOW,
		  KEYWORDS_lookup_text(LONG_KW), NULL);
    else {
        sscanf((char *)nidl_yytext, "%ld", &nidl_yylval.y_int_info.int_val);
    }


    if ((nidl_yytext[0] == '0') && (strlen((char *)nidl_yytext) != strspn((char *)nidl_yytext,"01234567"))) {
        char const *int_text;           /* Text of integer */
        STRTAB_str_t string_id;         /* Entry in string table of integer */
        string_id = STRTAB_add_string(nidl_yytext);
        STRTAB_str_to_string(string_id, &int_text);
        acf_error(nidl_yylineno, NIDL_INVOCTDIGIT, int_text, NULL);
    }

    return(INTEGER_NUMERIC);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 414 "nidl_l.l"
{
     int unsigned_int = true;
    /*
    ** Remove suffix for long and/or unsigned, if present
    */ 
    if ((nidl_yytext[nidl_yyleng-1] == 'L') ||
        (nidl_yytext[nidl_yyleng-1] == 'l') ||
        (nidl_yytext[nidl_yyleng-1] == 'U') ||
        (nidl_yytext[nidl_yyleng-1] == 'u'))
     {
          if (nidl_yytext[nidl_yyleng-1] == 'U' || nidl_yytext[nidl_yyleng-1] == 'u')
                unsigned_int = true;
          nidl_yytext[nidl_yyleng-1] = '\0'; 
          if ((nidl_yytext[nidl_yyleng-2] == 'L') ||
                     (nidl_yytext[nidl_yyleng-2] == 'l') ||
                     (nidl_yytext[nidl_yyleng-2] == 'U') ||
                     (nidl_yytext[nidl_yyleng-2] == 'u'))
          {
                if (nidl_yytext[nidl_yyleng-2] == 'U' || nidl_yytext[nidl_yyleng-2] == 'u')
                     unsigned_int = true;

                nidl_yytext[nidl_yyleng-2] = '\0';
          }
     }

    /*
    ** Scan the hex integer and return the value as an integer
    */
    sscanf((char *)&nidl_yytext[2],"%lx", &nidl_yylval.y_int_info.int_val);
     nidl_yylval.y_int_info.int_signed = !unsigned_int;
    return(INTEGER_NUMERIC);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 446 "nidl_l.l"
{
    nidl_yylval.y_float = STRTAB_add_string((char *)nidl_yytext);
    return(FLOAT_NUMERIC);
}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 451 "nidl_l.l"
{   return (yyuuid((char *)&nidl_yytext[1], &nidl_yylval.y_uuid)); }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 452 "nidl_l.l"
{   return (yyolduuid((char *)&nidl_yytext[1], &nidl_yylval.y_uuid)); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 453 "nidl_l.l"
{   return (UNKNOWN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 455 "nidl_l.l"
ECHO;
	YY_BREAK
#line 1635 "nidl_l.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed nidl_yyin at a new source and called
			 * nidl_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = nidl_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( nidl_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * nidl_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of nidl_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					nidl_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			nidl_yyrestart(nidl_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) nidl_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 172 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 172 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 171);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up nidl_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --nidl_yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					nidl_yyrestart(nidl_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( nidl_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve nidl_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    nidl_yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void nidl_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        nidl_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            nidl_yy_create_buffer(nidl_yyin,YY_BUF_SIZE );
	}

	nidl_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	nidl_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void nidl_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		nidl_yypop_buffer_state();
	 *		nidl_yypush_buffer_state(new_buffer);
     */
	nidl_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	nidl_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (nidl_yywrap()) processing, but the only time this flag
	 * is looked at is after nidl_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void nidl_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	nidl_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE nidl_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) nidl_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nidl_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) nidl_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in nidl_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	nidl_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with nidl_yy_create_buffer()
 * 
 */
    void nidl_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		nidl_yyfree((void *) b->yy_ch_buf  );

	nidl_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a nidl_yyrestart() or at EOF.
 */
    static void nidl_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	nidl_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then nidl_yy_init_buffer was _probably_
     * called from nidl_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void nidl_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		nidl_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void nidl_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	nidl_yyensure_buffer_stack();

	/* This block is copied from nidl_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from nidl_yy_switch_to_buffer. */
	nidl_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void nidl_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	nidl_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		nidl_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void nidl_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)nidl_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nidl_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)nidl_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nidl_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE nidl_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) nidl_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nidl_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	nidl_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to nidl_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       nidl_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE nidl_yy_scan_string (yyconst char * yystr )
{
    
	return nidl_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to nidl_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE nidl_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) nidl_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in nidl_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = nidl_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in nidl_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nidl_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		nidl_yytext[nidl_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = nidl_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		nidl_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int nidl_yyget_lineno  (void)
{
        
    return nidl_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *nidl_yyget_in  (void)
{
        return nidl_yyin;
}

/** Get the output stream.
 * 
 */
FILE *nidl_yyget_out  (void)
{
        return nidl_yyout;
}

/** Get the length of the current token.
 * 
 */
int nidl_yyget_leng  (void)
{
        return nidl_yyleng;
}

/** Get the current token.
 * 
 */

char *nidl_yyget_text  (void)
{
        return nidl_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void nidl_yyset_lineno (int  line_number )
{
    
    nidl_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see nidl_yy_switch_to_buffer
 */
void nidl_yyset_in (FILE *  in_str )
{
        nidl_yyin = in_str ;
}

void nidl_yyset_out (FILE *  out_str )
{
        nidl_yyout = out_str ;
}

int nidl_yyget_debug  (void)
{
        return nidl_yy_flex_debug;
}

void nidl_yyset_debug (int  bdebug )
{
        nidl_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from nidl_yylex_destroy(), so don't allocate here.
     */

    /* We do not touch nidl_yylineno unless the option is enabled. */
    nidl_yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    nidl_yyin = stdin;
    nidl_yyout = stdout;
#else
    nidl_yyin = (FILE *) 0;
    nidl_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * nidl_yylex_init()
     */
    return 0;
}

/* nidl_yylex_destroy is for both reentrant and non-reentrant scanners. */
int nidl_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		nidl_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		nidl_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	nidl_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * nidl_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *nidl_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *nidl_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void nidl_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see nidl_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 455 "nidl_l.l"



void commenteof()
{
    log_error (nidl_yylineno, NIDL_COMMENTEOF, NULL);
    nidl_terminate();
}


static void yymark()
{
    char    *source ; /* Source file name in #line directive */
    int prev_lineno = nidl_yylineno - 1;

    source = NEW_VEC (char, nidl_yyleng);
    source[0] ='\0';
    /* If the format wasn't # line {int} {string}, then reparse without "line" identifier */
    if (sscanf((char *)nidl_yytext, "# line %d %s", &nidl_yylineno, source) < 1)
    {
	if (sscanf((char *)nidl_yytext, "# %d %s", &nidl_yylineno, source) < 1)
        {
            acf_warning(prev_lineno, NIDL_CPPCMDOPT,
#ifdef VMS
                (CMD_DCL_interface) ? "/PREPROCESS" :
#endif
                "-cpp_cmd", NULL);
        }
    }

    /* If text included a source file name, set name for error reporting. */
    if (source[0] != '\0'
        &&  !(source[0] == '"' && source[1] == '"'))
    {
        char    file_name[max_string_len];

        /* Strip the quotes. */
        strcpy(file_name, &source[1]);
        file_name[strlen(file_name)-1] = '\0';

        set_name_for_errors(file_name);
    }

    FREE(source);
}

static void read_c_comment()
{
    register int c;

    /* While not EOF look for end of comment */
    while ((c = input()))
    {
        if (c == '*')
        {
            if ((c = input()) == '/')
                break ;
            else
                yyunput(c, nidl_yytext) ;
        }
    }

    /* Didn't find end comment before EOF, issue error */
    if (c == 0) commenteof();
}


static int yyolduuid(s, uuid)
char *s;
nidl_uuid_t *uuid;
{
    unsigned32 v1_time_high;
    unsigned32 v1_time_low;
    unsigned32 v1_reserved = 0;  /* v1 UUID always zero here */
    unsigned32 v1_family;
    unsigned32 v1_host[7];
    int        i;
    char *uuid_str;

    if (sscanf(s, "%8X%4X.%2X.%2X.%2X.%2X.%2X.%2X.%2X.%2X",
              &v1_time_high, &v1_time_low, &v1_family,
              &v1_host[0], &v1_host[1], &v1_host[2], &v1_host[3],
              &v1_host[4], &v1_host[5], &v1_host[6]) != 10)
        acf_error(nidl_yylineno, NIDL_SYNTAXUUID, NULL);

    /* scanf only returns ints, so scan into ints and copy into smaller types */
    uuid->time_low                  = v1_time_high;
    uuid->time_mid                  = v1_time_low;
    uuid->time_hi_and_version       = v1_reserved;
    uuid->clock_seq_hi_and_reserved = v1_family;
    uuid->clock_seq_low             = v1_host[0];

    for (i=0; i < 6; i++)
        uuid->node[i] = v1_host[i+1];

    uuid_str = (char *)malloc(sizeof("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"));

    sprintf(uuid_str, "%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X",
              uuid->time_low, uuid->time_mid, uuid->time_hi_and_version,
              uuid->clock_seq_hi_and_reserved, uuid->clock_seq_low,
              uuid->node[0], uuid->node[1], uuid->node[2],
              uuid->node[3], uuid->node[4], uuid->node[5]);

    acf_warning(nidl_yylineno, NIDL_OLDUUID, NULL);
    acf_warning(nidl_yylineno, NIDL_NEWUUID, uuid_str, NULL);
    return (UUID_REP) ;
}

static int yyuuid(s, uuid)
char *s;
nidl_uuid_t *uuid;
{
    int i;
    unsigned32 time_low, time_mid, time_hi_and_version,
              clock_seq_hi_and_reserved, clock_seq_low,
              node[6];

    if (sscanf(s, "%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X",
              &time_low, &time_mid, &time_hi_and_version,
              &clock_seq_hi_and_reserved, &clock_seq_low,
              &node[0], &node[1], &node[2],
              &node[3], &node[4], &node[5]) != 11)
        acf_error(nidl_yylineno, NIDL_SYNTAXUUID, NULL);

    /* scanf only returns ints, so scan into ints and copy into smaller types */
    uuid->time_low = time_low;
    uuid->time_mid = time_mid;
    uuid->time_hi_and_version = time_hi_and_version;
    uuid->clock_seq_hi_and_reserved = clock_seq_hi_and_reserved;
    uuid->clock_seq_low = clock_seq_low;
    for (i=0; i < 6; i++)
        uuid->node[i] = node[i];
    return (UUID_REP);
}

#ifdef FLEX_SCANNER
/*****************************************************************
 *
 *  Helper functions for managing multiple FLEX contexts
 *
 *  GNU FLEX support for DCE 1.2.2 idl_compiler
 *  added 07-11-97 Jim Doyle, Boston University, <jrd@bu.edu>
 *
 *  Maintainance note:
 *
 *    The set of flex-specific static and global variables
 *    managed by the following code may need to be changed
 *    for versions of FLEX newer or later than v2.5.4. This
 *    code was tested with Flex 2.4.6 and 2.5.4. V2.4 of FLEX
 *    defined three static variables (yy_start_stack,
 *    yy_start_stack_depth,yy_start_stack_ptr). In V2.5 of FLEX,
 *    these three statics disappeared. Fortunately FLEX defined
 *    macros YY_FLEX_MANOR_VERSION and YY_FLEX_MINOR_VERSION.
 *    These are helpful for conditionally compiling in support for
 *    several vintages of FLEX.
 *
 *
 *****************************************************************/

/*****************************************************************
 *
 * Data structure to store the state of a FLEX lexxer context
 *
 *****************************************************************/

struct nidl_flexxer_state_data {

/*
   * flex statics - hidden from the outside world. These are
   * generated by flex.
   *
   * MAINTAINANCE NOTE:  In versions later or earlier than 2.5.4,
   * the exact set of static variables that FLEX generates may be
   * different than is what is defined here. In that case, generate
   * the lexxer (i.e. flex nidl.l), grep the resulting generated C
   * flexxer for the word 'static'. You can then determine what
   * variables are new, dont exist, or have been renamed. Another
   * alternative for learning the names of all the static and global
   * variables used by the flexxer - is to compile the stub and
   * examine the object table dump (i.e using nm(1) on the .o file).
   *
   */

  YY_BUFFER_STATE yy_current_buffer;
  char            yy_hold_char;
  int             yy_n_chars;
  char          * yy_c_buf_p;
  int             yy_init;
  int             yy_start;
  int             yy_did_buffer_switch_on_eof;
#ifdef YY_USES_REJECT
  yy_state_type  *yy_state_ptr;
  char           *yy_full_match;
  int		  yy_lp;
#else
  yy_state_type   yy_last_accepting_state;
  char          * yy_last_accepting_cpos;
#endif
  int             yy_more_flag;
  int             yy_more_len;

 #if (YY_FLEX_MAJOR_VERSION == 2) && (YY_FLEX_MINOR_VERSION == 4)
  int             yy_start_stack_ptr;
  int             yy_start_stack_depth;
  int           * yy_start_stack;
 #endif

  /*
   * flex globals - visible to the outside world
   *
   */

  FILE          * nidl_yyin;
  FILE          * nidl_yyout;
  int             nidl_yylineno;
  YYSTYPE         yylval;
  int             nidl_yyleng;
  char          * nidl_yytext;

};

typedef struct nidl_flexxer_state_data nidl_flexxer_activation_record;

/*****************************************************************
 *
 * Basic constructors/destructors for FLEX activation states
 *
 *****************************************************************/

void *
new_nidl_flexxer_activation_record()
  {
    return (malloc(sizeof(nidl_flexxer_activation_record)));
  }

void
delete_nidl_flexxer_activation_record(void * p)
{
 if (p)
  {
    /* Note: Never call nidl_yy_free_buffer(yy_current_buffer)
     * from here to delete the Flex internal buffer context.
     * you will get a hard to diagnose bug. Instead, nidl_yywrap()
     * should call the delete function for the buffer. I know,
     * it is tempting to put all the 'destructors' in one place,
     * however, this is NOT a good place to do it.
     * jrd@bu.edu  07-12-97 04:30
     */
    free((void *)p);
  }
}

/*****************************************************************
 *
 * Get/Set/Initialize methods
 *
 *****************************************************************/

void *
get_current_nidl_flexxer_activation()
  {
    nidl_flexxer_activation_record * p;

    p = (nidl_flexxer_activation_record * )
                new_nidl_flexxer_activation_record();

    /* 
     * save the statics internal to the flexxer
     *
     */

    nidl_yyensure_buffer_stack();
  #if (YY_FLEX_MAJOR_VERSION == 2) && (YY_FLEX_MINOR_VERSION == 5)
    p->yy_current_buffer = YY_CURRENT_BUFFER;
  #else
    p->yy_current_buffer = YY_CURRENT_BUFFER_LVALUE;
  #endif
    p->yy_hold_char = yy_hold_char;
    p->yy_n_chars = yy_n_chars;
    p->yy_c_buf_p = yy_c_buf_p;
    p->yy_init = yy_init;
    p->yy_start = yy_start;
    p->yy_did_buffer_switch_on_eof = yy_did_buffer_switch_on_eof;
#ifdef YY_USES_REJECT
    p->yy_state_ptr = yy_state_ptr;
    p->yy_full_match = yy_full_match;
    p->yy_lp = yy_lp;
#else
    p->yy_last_accepting_state = yy_last_accepting_state;
    p->yy_last_accepting_cpos = yy_last_accepting_cpos;
#endif
    p->yy_more_flag = yy_more_flag;
    p->yy_more_len = yy_more_len;

    /* FLEX 2.5 does not have these variables.
     * FLEX 2.4 does have them though...
     */

  #if (YY_FLEX_MAJOR_VERSION == 2) && (YY_FLEX_MINOR_VERSION == 4)
    p->yy_start_stack_ptr = yy_start_stack_ptr;
    p->yy_start_stack_depth = yy_start_stack_depth;
    p->yy_start_stack = yy_start_stack;
  #endif

    /*
     * save the globals, these are visible outside the scope
     * of the lexxer
     *
     */

    p->nidl_yyin = nidl_yyin;
    p->nidl_yyout = nidl_yyout;
    p->nidl_yylineno = nidl_yylineno;
    p->yylval = nidl_yylval;
    p->nidl_yyleng = nidl_yyleng;
    p->nidl_yytext = nidl_yytext;


    return (void *)p;
  }


void
set_current_nidl_flexxer_activation(void * ptr)
  {

    nidl_flexxer_activation_record * p = (nidl_flexxer_activation_record *)ptr;

    // restore the statics

    YY_CURRENT_BUFFER_LVALUE = p->yy_current_buffer;
    yy_hold_char = p->yy_hold_char;
    yy_n_chars = p->yy_n_chars;
    yy_c_buf_p = p->yy_c_buf_p;
    yy_init = p->yy_init;
    yy_start = p->yy_start;
    yy_did_buffer_switch_on_eof = p->yy_did_buffer_switch_on_eof;
#ifdef YY_USES_REJECT
    yy_state_ptr = p->yy_state_ptr;
    yy_full_match = p->yy_full_match;
    yy_lp = p->yy_lp;
#else
    yy_last_accepting_state = p->yy_last_accepting_state;
    yy_last_accepting_cpos = p->yy_last_accepting_cpos;
#endif
    yy_more_flag = p->yy_more_flag;
    yy_more_len = p->yy_more_len;

    /* FLEX 2.5 does not have these variables.
     * FLEX 2.4 does have them though...
     */

  #if (YY_FLEX_MAJOR_VERSION == 2) && (YY_FLEX_MINOR_VERSION == 4)
    yy_start_stack_ptr = p->yy_start_stack_ptr;
    yy_start_stack_depth = p->yy_start_stack_depth;
    yy_start_stack = p->yy_start_stack;
  #endif

    /*
     * save the globals, these are visible outside the scope
     * of the lexxer
     *
     */

    nidl_yyin = p->nidl_yyin;
    nidl_yyout = p->nidl_yyout;
    nidl_yylineno = p->nidl_yylineno;
    nidl_yylval = p->yylval;
    nidl_yyleng = p->nidl_yyleng;
    nidl_yytext = p->nidl_yytext;


  }

void
init_new_nidl_flexxer_activation(void)
  {
    /*
     * set some initial conditions for a new FLEXER state
     * These were gleaned by looking at the compile-time 
     * initializations in the generated nidl_lex_yy.c file.
     *
     */

    nidl_yyensure_buffer_stack();
    YY_CURRENT_BUFFER_LVALUE = 0;
    yy_c_buf_p = (char *) 0;
    yy_init = 0;
    yy_start = 0;
    yy_more_flag = 0;
    yy_more_len = 0;


    /* FLEX 2.5 does not have these variables.
     * FLEX 2.4 does have them though...
     */

  #if (YY_FLEX_MAJOR_VERSION == 2) && (YY_FLEX_MINOR_VERSION == 4)
    yy_start_stack_ptr = 0;
    yy_start_stack_depth = 0;
    yy_start_stack = 0;
  #endif

    /*
     * Set the globals to reasonable states
     */

    nidl_yyin = NULL;
    nidl_yyout = NULL;
    nidl_yylineno = 1;
    nidl_yyleng = 0;


  }

#endif /* FLEX_SCANNER */
/* preserve coding style vim: set tw=78 sw=4 : */

