/* Generated by IDL compiler version FreeDCE 1.0.1 64-bit with GNU Flex/Bison */
#ifndef perfg_v1_0_included
#define perfg_v1_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
extern void perfg_op1(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ idl_ulong_int n,
    /* [out] */ idl_ulong_int *x
#endif
);
extern void perfg_op2(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ idl_ulong_int n,
    /* [out] */ idl_ulong_int *x
#endif
);
typedef struct perfg_v1_0_epv_t {
	void (*perfg_op1)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ idl_ulong_int n,
    /* [out] */ idl_ulong_int *x
#endif
);
	void (*perfg_op2)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ idl_ulong_int n,
    /* [out] */ idl_ulong_int *x
#endif
);
} perfg_v1_0_epv_t;
extern rpc_if_handle_t perfg_v1_0_c_ifspec;
extern rpc_if_handle_t perfg_v1_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
