/* Generated by IDL compiler version FreeDCE 1.1.0.7 64-bit with GNU Flex/Bison */
#ifndef perfc_v2_0_included
#define perfc_v2_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
extern void perfc_init(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [out] */ idl_ulong_int *p
#endif
);
extern void perfc_cb(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [out] */ idl_ulong_int *c
#endif
);
extern void perfc_cb_idem(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [out] */ idl_ulong_int *c
#endif
);
typedef struct perfc_v2_0_epv_t {
	void (*perfc_init)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [out] */ idl_ulong_int *p
#endif
);
	void (*perfc_cb)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [out] */ idl_ulong_int *c
#endif
);
	void (*perfc_cb_idem)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [out] */ idl_ulong_int *c
#endif
);
} perfc_v2_0_epv_t;
extern rpc_if_handle_t perfc_v2_0_c_ifspec;
extern rpc_if_handle_t perfc_v2_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
