/* Generated by IDL compiler version FreeDCE 1.0.1 64-bit with GNU Flex/Bison */
#ifndef echo_v1_0_included
#define echo_v1_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
typedef idl_char *string_t;
typedef struct  {
unsigned32 argc;
string_t argv[1];
} args;
extern idl_boolean ReverseIt(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ args *in_text,
    /* [out] */ args **out_text,
    /* [out] */ error_status_t *status
#endif
);
typedef struct echo_v1_0_epv_t {
    idl_boolean (*ReverseIt)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ args *in_text,
    /* [out] */ args **out_text,
    /* [out] */ error_status_t *status
#endif
);
} echo_v1_0_epv_t;
extern rpc_if_handle_t echo_v1_0_c_ifspec;
extern rpc_if_handle_t echo_v1_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
