/* Generated by IDL compiler */
#ifndef IRemoteActivation_v0_0_included
#define IRemoteActivation_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef ObjectRpcBaseTypes_v0_0_included
#include <dce/obase.h>
#endif
#define MODE_GET_CLASS_OBJECT (0xffffffff)
extern HRESULT RemoteActivation(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hRpc,
    /* [in] */ ORPCTHIS *ORPCthis,
    /* [out] */ ORPCTHAT *ORPCthat,
    /* [in] */ GUID *Clsid,
    /* [in] */ idl_byte *pwszObjectName,
    /* [in] */ MInterfacePointer *pObjectStorage,
    /* [in] */ DWORD ClientImpLevel,
    /* [in] */ DWORD Mode,
    /* [in] */ DWORD Interfaces,
    /* [in] */ IID *pIIDs,
    /* [in] */ idl_ushort_int cRequestedProtseqs,
    /* [in] */ idl_ushort_int RequestedProtseqs[],
    /* [out] */ OXID *pOxid,
    /* [out] */ DUALSTRINGARRAY **ppdsaOxidBindings,
    /* [out] */ IPID *pipidRemUnknown,
    /* [out] */ DWORD *pAuthnHint,
    /* [out] */ COMVERSION *pServerVersion,
    /* [out] */ HRESULT *phr,
    /* [out] */ MInterfacePointer **ppInterfaceData,
    /* [out] */ HRESULT *pResults
#endif
);
typedef struct IRemoteActivation_v0_0_epv_t {
	HRESULT (*RemoteActivation)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hRpc,
    /* [in] */ ORPCTHIS *ORPCthis,
    /* [out] */ ORPCTHAT *ORPCthat,
    /* [in] */ GUID *Clsid,
    /* [in] */ idl_byte *pwszObjectName,
    /* [in] */ MInterfacePointer *pObjectStorage,
    /* [in] */ DWORD ClientImpLevel,
    /* [in] */ DWORD Mode,
    /* [in] */ DWORD Interfaces,
    /* [in] */ IID *pIIDs,
    /* [in] */ idl_ushort_int cRequestedProtseqs,
    /* [in] */ idl_ushort_int RequestedProtseqs[],
    /* [out] */ OXID *pOxid,
    /* [out] */ DUALSTRINGARRAY **ppdsaOxidBindings,
    /* [out] */ IPID *pipidRemUnknown,
    /* [out] */ DWORD *pAuthnHint,
    /* [out] */ COMVERSION *pServerVersion,
    /* [out] */ HRESULT *phr,
    /* [out] */ MInterfacePointer **ppInterfaceData,
    /* [out] */ HRESULT *pResults
#endif
);
} IRemoteActivation_v0_0_epv_t;
extern IRemoteActivation_v0_0_epv_t IRemoteActivation_v0_0_c_epv;
extern rpc_if_handle_t IRemoteActivation_v0_0_c_ifspec;
extern rpc_if_handle_t IRemoteActivation_v0_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
